version: '3.8'

services:
  app:
    build:
      args:
        MODE: 'dev'
    command: |
      bash -c '
        if [ "$SSH_DEBUG" == "true" ]
        then
          apt-get update
          apt-get install -y openssh-server

          mkdir -p /var/run/sshd
          echo root:password | chpasswd
          sed -i "s/#PermitRootLogin prohibit-password/PermitRootLogin yes/" /etc/ssh/sshd_config

          echo Waiting for ssh-connections...
          /usr/sbin/sshd -D
        else
          sleep 10 && make runserver
        fi
      '
    environment:
      SSH_DEBUG: 'true'
    ports:
      - 2222:22

  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - 8081:8080

#  todo: понять, как работать с файлами (они будут сохраняться в волюм?) Понять, что делать с кэшем
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/docs/openapi.yaml
    volumes:
      - ./docs/openapi.yaml:/docs/openapi.yaml
    ports:
      - 8082:8080
    depends_on:
      - app
